language: c

addons:
  apt:
    sources:
    - ubuntu-sdk-team
#    - libsodium
    packages:
    - qt5-qmake
    - autotools-dev
    - automake
    - pkg-config
    - libopus-dev
    - libvpx-dev 
#   - libsodium-dev
    - libsndfile1-dev
#    - libtoxcore-dev
#    - libtoxav-dev

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then sh ./travis/linux-before.sh;   fi
  
script: 
  - qmake -config suit
  - make
  - qmake -config toxdatatool
  - make

notifications:
  email: false
