language: c

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - qt5-default
    - autotools-dev
    - automake
    - libsodium-dev
    
script: 
  - qmake -config suit
  - make
  - qmake -config toxdatatool
  - make

notifications:
  email: false
