language: c

addons:
  apt:
    sources:
    - ubuntu-sdk-team
#    - libsodium
    packages:
    - qt5-default
    - autotools-dev
    - automake
    - pkg-config
    - libopus-dev
    - libvpx-dev
    - libpopt-dev
    - libsndfile1-dev
# missing :
#   - libsodium-dev
#    - libtoxcore-dev
#    - libtoxav-dev

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then sh ./travis/linux-before.sh;   fi
  
script:
  - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then export PKG_CONFIG_PATH="$(pwd)/TRAVIS_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"; fi
  - echo $PKG_CONFIG_PATH
  - /lib/libc.so.6
  - qmake -v
  - qmake -config suit
  - make
  - make distclean
  - qmake -config toxdatatool
  - make
  - make distclean

notifications:
  email: false
