#############################################################################
# Makefile for building: suit
# Generated by qmake (2.01a) (Qt 4.8.7) on: sam. avr. 30 22:27:04 2016
# Project:  ToxSuite.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -config suit -o Makefile ToxSuite.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGIT_VERSION=\"57967bf7-dirty\"
CFLAGS        = -std=gnu99 -Wno-unused-parameter -Wno-unused-result -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   src/captcha/libcaptcha.o -lsndfile -ltoxav -lopus -lvpx -ltoxdns -ltoxencryptsave -ltoxcore -lsodium -lm -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/call.c \
		src/command.c \
		src/suit.c \
		src/jsmn/jsmn.c \
		src/file.c \
		src/friend.c \
		src/toxdata.c \
		src/ylog/ylog.c \
		src/timespec.c \
		src/misc.c 
OBJECTS       = call.o \
		command.o \
		suit.o \
		jsmn.o \
		file.o \
		friend.o \
		toxdata.o \
		ylog.o \
		timespec.o \
		misc.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ToxSuite.pro
QMAKE_TARGET  = suit
DESTDIR       = 
TARGET        = suit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .buildfile $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ToxSuite.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -config suit -o Makefile ToxSuite.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -config suit -o Makefile ToxSuite.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/suit1.0.0 || $(MKDIR) .tmp/suit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/suit1.0.0/ && (cd `dirname .tmp/suit1.0.0` && $(TAR) suit1.0.0.tar suit1.0.0 && $(COMPRESS) suit1.0.0.tar) && $(MOVE) `dirname .tmp/suit1.0.0`/suit1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/suit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


.buildfile:
	make -f src/captcha/Makefile

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

call.o: src/call.c src/call.h \
		src/suit.h \
		src/friend.h \
		src/list.h \
		src/misc.h \
		src/file.h \
		src/ylog/ylog.h \
		src/timespec.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o call.o src/call.c

command.o: src/command.c src/suit.h \
		src/friend.h \
		src/list.h \
		src/misc.h \
		src/file.h \
		src/ylog/ylog.h \
		src/unused.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o command.o src/command.c

suit.o: src/suit.c src/suit.h \
		src/friend.h \
		src/list.h \
		src/misc.h \
		src/call.h \
		src/command.h \
		src/file.h \
		src/ylog/ylog.h \
		src/toxdata.h \
		src/timespec.h \
		src/unused.h \
		src/jsmn/jsmn.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o suit.o src/suit.c

jsmn.o: src/jsmn/jsmn.c src/jsmn/jsmn.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jsmn.o src/jsmn/jsmn.c

file.o: src/file.c src/file.h \
		src/ylog/ylog.h \
		src/unused.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o file.o src/file.c

friend.o: src/friend.c src/friend.h \
		src/list.h \
		src/toxdata.h \
		src/ylog/ylog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o friend.o src/friend.c

toxdata.o: src/toxdata.c src/toxdata.h \
		src/friend.h \
		src/list.h \
		src/ylog/ylog.h \
		src/unused.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o toxdata.o src/toxdata.c

ylog.o: src/ylog/ylog.c src/ylog/ylog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ylog.o src/ylog/ylog.c

timespec.o: src/timespec.c src/timespec.h \
		src/ylog/ylog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o timespec.o src/timespec.c

misc.o: src/misc.c src/misc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o misc.o src/misc.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

